name: CI-test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: astal-sh/setup-uv@v5
        with:
          version: "0.6.5"
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: uv run pytest
